### ISSUE TITLE
.get() call on index.html

### ISSUE THREAD

**Issue by dgatto** [user2745/pi-server#2]
In this line of code: 

`app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, "/", "index.html"));
    res.status(200);
});`

you manually handle the `GET` request of `/`. It turns out that this call never gets hit. I believe this is because the file is already named `index.html`, and browsers, in their architecture, just expect there to be a file with that name (I think? Don't quote me on that). If I change the name to `main.html`, the `.get` fires off. I don't know why this would make a difference, I would still assume the call to be made but just for the `.sendFile()` to not happen? Idk tho, changing the file name made a difference.

The question is, do you want to keep this implementation and manually handle the `GET` request, changing the file name to something besides `index.html`, or do you want to delete that `.get` function altogether and let the browser handle it?

**Comment by user2745** [comment]
that's a great point, I never even noticed that -- if the fix is compatible with NodeJS hosting solutions then I'm for it

**Comment by user2745** [comment]
tested it out, works well -- I'll move this into a PR
